== Repository Creation Process

=== Install "nvm"

https://github.com/nvm-sh/nvm

==== Windows 

(nodejs + npm)
via NVM (node version manager)
https://github.com/coreybutler/nvm-windows/releases

==== Linux

(nodejs + npm)
via NVM (node version manager)
[]

clone this repo in the root of your user profile
cd ~/ from anywhere then 
----
git clone https://github.com/nvm-sh/nvm.git .nvm
----
----
cd ~/.nvm
----
and check out the latest version with 
----
git checkout v0.38.0
----

activate nvm by sourcing it from your shell: 
----
. ./nvm.sh
----
Now add these lines to your ~/.bashrc, ~/.profile, or ~/.zshrc file to have it automatically sourced upon login: (you may have to add to more than one of the above files)

----
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
----

=== Set Node version

Create a .nvmrc file in root of repository

Add this entry to the new .nvmrc file

----
lts/*
----

=== Install yarn

// TODO provide directions for MacOS, Linux, Windows

=== Add dependencies

yarn add hardhat @nomiclabs/hardhat-waffle ethereum-waffle chai @nomiclabs/hardhat-ethers ethers @openzeppelin/test-helpers @types/chai @types/mocha @types/node hardhat-gas-reporter hardhat-typechain mocha nyc solidity-coverage solidity-docgen ts-node typescript chai-bn typechain ts-generator bn.js @codechecks/client hardhat-deploy chai-as-promised --dev

// TODO provide explanations for each package

=== Create directories

contracts - for Solidity code
test - for test code

